version: '3.8'

services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: app
      MONGO_INITDB_ROOT_PASSWORD: 1234
    networks:
      - db-network
    ports:
      - 27017:27017
    volumes:
      - db-volume:/data/db

  express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: app
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://app:1234@db:27017/
    networks:
      - db-network
    ports:
      - 8081:8081
    depends_on:
      - db

networks:
  db-network:

volumes:
  db-volume: