version: '3.8'

services:
  back:
    build: ./
    working_dir: /back
    ports:
      - '3000:3000'
    volumes:
      - ./:/back
    env_file:
      - ../.env
    depends_on:
      - db
    networks:
      - db-network
    restart: on-failure